Repository formzillion/formzillion.com, pull requests merged in 2023-05, with the labels that each got.

#10 feat: :sparkles: Added Mailchimp Auth and also Mailerlite auth plus updated the webhooks docs
  apps/docs/pages/integrations.mdx
  apps/docs/pages/integrations/webhooks.mdx
  apps/docs/public/integrations/sendgrid/auth.png
  apps/docs/public/integrations/slack/auth.png
  apps/docs/public/integrations/slack/connection.png
  apps/docs/public/integrations/webhooks/auth.png
  apps/docs/public/integrations/webhooks/connection.png
  apps/webapp/src/app/(portal)/[teamId]/[formId]/workflows/AddActionModal.tsx
  apps/webapp/src/app/(portal)/[teamId]/apps/page.tsx
  apps/webapp/src/app/(portal)/[teamId]/apps/zauth.ts
  apps/webapp/src/app/fetch/tasks/addTask.ts
  apps/webapp/src/pages/api/integrations/mailchimp-callback.ts
  apps/webapp/src/pages/api/integrations/mailchimp-sdk.ts
  apps/webapp/src/pages/api/tasks/add-task.ts
  turbo.json
Labels: new integration

#152 feat: :memo: Updated the Integrations Action Names
  apps/docs/components/ArrowIcon.tsx
  apps/docs/pages/integrations/_meta.json
  apps/docs/pages/integrations/automate-record-creation-in-airtable.mdx
  apps/docs/pages/integrations/automate-sendgrid-to-send-emails.mdx
  apps/docs/pages/integrations/automate-slack-notifications-for-form-submissions.mdx
  apps/docs/pages/integrations/automate-subscriber-addition-to-mailerlite.mdx
  apps/docs/pages/integrations/automate-the-transfer-of-form-data-to-webhooks-endpoint.mdx
  apps/docs/pages/integrations/automate-ticket-creation-in-freshdesk.mdx
  apps/docs/theme.config.tsx
  apps/website/src/app/shared/FooterV2.tsx
Labels: documentation, linear

#158 feat: :memo: Added Spam Protection Images to the Assets
  apps/docs/pages/index.mdx
  apps/docs/pages/setup/spam-protection/recaptcha-v2.mdx
  apps/docs/pages/setup/spam-protection/recaptcha-v3.mdx
  apps/docs/public/setup/spam-protection/re-captcha-creds.png
  apps/docs/public/setup/spam-protection/re-captcha-on-click.gif
  apps/docs/public/setup/spam-protection/re-captcha-v2-setup.png
  apps/docs/public/setup/spam-protection/re-captcha-v3-setup.png
Labels: documentation, linear

#159 Fixed TeamSwitcher
  apps/webapp/src/app/(auth)/login/page.tsx
  apps/webapp/src/app/(portal)/shared/TeamSwitcher.tsx
  apps/webapp/src/app/fetch/auth/login.ts
  apps/webapp/src/pages/api/auth/login.ts
Labels: enhancement

#170 feat: 🎨 demo page cereated and Demo form added
  apps/website/next.config.js
  apps/website/package.json
  apps/website/src/app/demo/SeeInAction.tsx
  apps/website/src/app/demo/page.tsx
  apps/website/src/app/home/WaitlistHeroSection/HeroLeft.tsx
  pnpm-lock.yaml
Labels: enhancement, feature

#226 Moved the Worker outside the workspace for deployment
  .github/workflows/dev-fz-worker.yml
  .github/workflows/prod-fz-worker.yml
  apps/webapp/src/app/f/[formId]/fzProducer.ts
  worker/.env.example
  worker/.eslintrc.js
  worker/.gitignore
  worker/Dockerfile
  worker/global.d.ts
  worker/index.ts
  worker/nodemon.json
  worker/package-lock.json
  worker/package.json
  worker/src/apps/airtable/index.ts
  worker/src/apps/convertkit/index.ts
  worker/src/apps/freshdesk/index.ts
  worker/src/apps/index.ts
  worker/src/apps/mailerlite/index.ts
  worker/src/apps/sendgrid/index.ts
  worker/src/apps/sendgrid/templates/newSubmission.ts
  worker/src/apps/sendgrid/templates/thankYou.ts
  worker/src/apps/sendgrid/templates/welcome.ts
  worker/src/apps/slack/index.ts
  worker/src/apps/slack/templates/newSubmission.ts
  worker/src/apps/webhooks/index.ts
  worker/src/config/index.ts
  worker/src/config/sengrid.ts
  worker/src/defaultActions.ts
  worker/src/helpers/getTeamSlug.ts
  worker/src/processor.ts
  worker/src/types/index.d.ts
  worker/src/worker.ts
  worker/tsconfig.json
  worker/utils/bull-mq.ts
  worker/utils/http-client.ts
  worker/utils/index.ts
  worker/utils/logger.ts
Labels: linear, High priority

#233 fix: :zap: Removed the nested folder structure for the worker
  .github/workflows/dev-fz-worker.yml
  .github/workflows/prod-fz-worker.yml
  worker/Dockerfile
Labels: linear

#236 perf: :zap: Added the condition for the processing the worker actions
  apps/webapp/src/app/f/[formId]/route.ts
Labels: linear, Medium priority

#244 fix: :loud_sound: Added Logs for Verifying the Slack Connection Status in Developement
  apps/webapp/src/lib/integrationsCallbackHelper.ts
  apps/webapp/src/pages/api/integrations/slack-callback.ts
  apps/webapp/src/pages/api/integrations/slack-sdk.ts
Labels: bug, linear

#243 feat: :passport_control: Added reset-password route in the middleware
  apps/webapp/src/middleware.ts
Labels: bug, linear

#249 feat: 🎨 logos added for compareSection And added compare Pages to footer
  apps/website/public/brands/basin.png
  apps/website/public/brands/formCarry.svg
  apps/website/public/brands/formspark.webp
  apps/website/public/brands/formspree.png
  apps/website/public/brands/getform.svg
  apps/website/src/app/compare/[slug]/CompareSection.tsx
  apps/website/src/app/compare/[slug]/HeroSection.tsx
  apps/website/src/app/shared/FooterV2.tsx
Labels: enhancement, linear, Improvement

#253 fix: 🎨 docs link change from fixed to Env and footer links for compare pages
  apps/website/src/app/demo/Features.tsx
  apps/website/src/app/features/[slug]/page.tsx
  apps/website/src/app/home/CustomizeSection.tsx
  apps/website/src/app/home/Features/FeaturesTab.tsx
  apps/website/src/app/home/Features/Redirects/RedirectsDescription.tsx
  apps/website/src/app/home/Features/SpamFilters/SpamFiltersDescription.tsx
  apps/website/src/app/home/FeaturesOverviewNew/index.tsx
  apps/website/src/app/integrations/[slug]/content/heroSection.tsx
  apps/website/src/app/platforms/[slug]/page.tsx
  apps/website/src/app/shared/CTASection.tsx
  apps/website/src/app/shared/DisclosureNav.tsx
  apps/website/src/app/shared/FooterV2.tsx
  apps/website/src/app/shared/Header.tsx
  apps/website/src/app/shared/HeaderV1.tsx
  apps/website/src/app/shared/HeaderV2.tsx
Labels: bug, enhancement
